#!/bin/bash
# this file is natively sourced by: GDM, LightDM, LXDM, SDDM

# use whatever environment bash expects
[[ -r ${HOME}/.bash_profile ]] && . "${HOME}/.bash_profile"

# run user-specific scripts
if [[ -d ${HOME}/.xprofile.d ]]; then
    for f in "${HOME}/.xprofile.d"/*; do
        [[ -x ${f} ]] && . "${f}"
    done
    unset f
fi

# apply default output profile (and wallpaper)
command -v ns-gui-utility &>/dev/null && ns-gui-utility output-profile -d

# X settings
xset s off  # disable screen blanking
xset -dpms  # disable dpms

# Setup and clear logs for startup services
DISPLAY_SERVICE_LOG_DIR="$(realpath -q "${BASH_SOURCE[0]}")"
DISPLAY_SERVICE_LOG_DIR="${DISPLAY_SERVICE_LOG_DIR%/*}/logs"
if [[ -d ${DISPLAY_SERVICE_LOG_DIR} ]]; then
    # clear it
    rm "${DISPLAY_SERVICE_LOG_DIR}"/*
else
    DISPLAY_SERVICE_LOG_DIR="/tmp"
fi
export DISPLAY_SERVICE_LOG_DIR

# background services
pushd "${DISPLAY_SERVICE_LOG_DIR}" &>/dev/null
command -v blueman-applet &>/dev/null && blueman-applet &>blueman-applet.log &
command -v cbatticon &>/dev/null && cbatticon &>cbatticon.log &
command -v steam &>/dev/null && steam -silent &>steam.log &
popd &>/dev/null
